### ISSUE TITLE
[TO-DO] Bliss 1.0.0

### ISSUE THREAD

**Issue by MrScautHD** [MrScautHD/Bliss#1]
<p align="center" style="margin-bottom: 0px !important;">
  <img width="512" src="https://github.com/user-attachments/assets/fc27500c-3bc6-4dc8-b78f-dba812353655" alt="Logo" align="center">
</p>

<h1 align="center" style="margin-top: 0px;">Greetings to Bliss-v1.0.0! 🎉</h1>
<h4 align="center">Delve into the to-do list outlining the enhancements and updates slated for the 1.0.0 release!</h4>

## Features
- [x] Add `IWindow` and based on that `Sdl3Window`.
- [x] Add `Logger` to handle the console output.
- [x] Add `Effect` to simplify shader loading.
- [x] Add `Texture2D` to draw textures.
- [x] Add `Cubemap` to draw cubemaps.
- [x] Add `Font` to draw text.
- [x] Add `Color` to get rid of `RgbaFloat` and `RgbaByte`.
- [x] Add `Vertex2D` and `Vertex3D`.
- [x] Add `Model` with draw method.
- [x] Add `Mesh`.
- [x] Add `BoundingBox`.
- [x] Add `Transform`.
- [x] Add `Camera3D`.
- [x] Add `Camera2D`.
- [x] Add `Frustum` to improve the performance.
- [x] Add `SpriteBatch` to textures and text.
- [x] Add `Primitive Batch` to render rectangles, circles...
- [x] Add `Input` to handle gamepad, keyboard, mouse.
- [x] Add `Gamepad` to simplify the controller implementation.
- [x] Add `MouseCursor` to change the state of the mouse cursor.
- [x] Add `Material` system.
- [x] Clean up `SpriteBatch`.
- [x] Add Multi Sampling.
- [x] Add `SetWindowIcon` method.

## Fix
- [x] Fix issue where the SpriteBatch sorting is wrong (`Texture1` get rendered above `Texture2`).
- [x] Fix issue where PrimitiveBatch.DrawEmptyRectangle(); is not rotating right!
