### ISSUE TITLE
[TO-DO] Bliss 1.0.1

### ISSUE THREAD

**Issue by MrScautHD** [MrScautHD/Bliss#3]
<p align="center" style="margin-bottom: 0px !important;">
  <img width="512" src="https://github.com/user-attachments/assets/fc27500c-3bc6-4dc8-b78f-dba812353655" alt="Logo" align="center">
</p>

<h1 align="center" style="margin-top: 0px;">Greetings to Bliss-v1.0.1! 🎉</h1>
<h4 align="center">Delve into the to-do list outlining the enhancements and updates slated for the 1.0.1 release!</h4>

## Features
- [ ] Add `Model Animation system`.
- [ ] Add `Gif system`
- [ ] Add `Media` system (https://github.com/cloudofoz/raylib-media)
- [ ] Finish open todos.
